app:
  src: src
  data: data
  model: model
entities:
  - name: Countries
    primaryKey: ["iso3"]
    uniqueKey: ["name"]
    properties:
      - name: name
        required: true
      - name: iso3
        required: true
        length: 3
    relations:
      - name: states
        type: manyToOne
        composite: true
        from: iso3
        entity: States
        to: countryCode
  - name: States
    primaryKey: ["id"]
    uniqueKey: ["countryCode", "name"]
    properties:
      - name: id
        type: integer
        required: true
      - name: name
        required: true
      - name: countryCode
        required: true
        length: 3
    relations:
      - name: country
        from: countryCode
        entity: Countries
        to: iso3
enums: []
sources:
  - name: test
    dialect: MySQL
    mapping: test
    connection:
      host: localhost
      port: 3309
      user: test
      password: test
      database: test
      multipleStatements: true
      waitForConnections: true
      connectionLimit: 10
      queueLimit: 0
mappings:
  - name: test
    entities: []
stages:
  - name: default
    sources:
      - name: test
views: []
