app:
  src: src
  data: data
  model: model
enums:
entities:
  - name: Address
    abstract: true
    indexes:
      - name: postalCode
        fields: ["postalCode"]
      - name: region
        fields: ["region", "country"]
      - name: city
        fields: ["city"]
    properties:
      - name: address
      - name: city
      - name: region
      - name: postalCode
        length: 20
      - name: country
  - name: Categories
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: name
        required: true
      - name: description
        length: 1000
  - name: Customers
    extends: Address
    primaryKey: ["id"]
    indexes:
      - name: name
        fields: ["name"]
    properties:
      - name: id
        length: 5
        required: true
      - name: name
        required: true
      - name: contact
      - name: phone
  - name: Employees
    extends: Address
    primaryKey: ["id"]
    uniqueKey: ["lastName", "firstName"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: lastName
        required: true
      - name: firstName
        required: true
      - name: title
      - name: titleOfCourtesy
      - name: birthDate
        type: dateTime
      - name: hireDate
        type: dateTime
      - name: phone
      - name: reportsToId
        type: integer
    relations:
      - name: reportsTo
        from: reportsToId
        entity: Employees
        to: id
  - name: Shippers
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: name
        required: true
      - name: phone
        length: 20
  - name: Suppliers
    extends: Address
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: name
        required: true
      - name: contact
      - name: phone
        length: 20
      - name: homepage
        length: 200
  - name: Products
    primaryKey: ["id"]
    uniqueKey: ["name", "supplierId"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: name
        required: true
      - name: supplierId
        required: true
        type: integer
      - name: categoryId
        type: integer
      - name: quantity
      - name: price
        type: decimal
        default: 0
      - name: inStock
        type: decimal
        default: 0
      - name: onOrder
        type: decimal
        default: 0
      - name: reorderLevel
        type: decimal
        default: 0
      - name: discontinued
        type: boolean
        default: false
    relations:
      - name: supplier
        from: supplierId
        entity: Suppliers
        to: id
        target: products
      - name: category
        from: categoryId
        entity: Categories
        to: id
        target: products
  - name: Orders
    primaryKey: ["id"]
    indexes:
      - name: orderDate
        fields: ["orderDate"]
      - name: shippedDate
        fields: ["shippedDate"]
    properties:
      - name: id
        type: integer
        required: true
        autoIncrement: true
      - name: customerId
        required: true
        length: 5
      - name: employeeId
        required: true
        type: integer
      - name: orderDate
        type: dateTime
      - name: requiredDate
        type: date
      - name: shippedDate
        type: date
      - name: shipViaId
        type: integer
      - name: freight
        type: decimal
      - name: name
      - name: address
      - name: city
      - name: region
      - name: postalCode
        length: 20
      - name: country
    relations:
      - name: customer
        from: customerId
        entity: Customers
        to: id
        target: orders
      - name: employee
        from: employeeId
        entity: Employees
        to: id
        target: orders
  - name: Orders.details
    primaryKey: ["orderId", "productId"]
    properties:
      - name: orderId
        required: true
        type: integer
      - name: productId
        required: true
        type: integer
      - name: unitPrice
        type: decimal
      - name: quantity
        type: decimal
      - name: discount
        type: decimal
    relations:
      - name: order
        from: orderId
        entity: Orders
        to: id
        target: details
        # targetComposite: true
      - name: product
        from: productId
        entity: Products
        to: id
        target: orderDetails
views:
  - name: default
mappings:
  - name: default
    entities:
      - name: Address
        abstract: true
        properties:
          - name: address
            mapping: Address
          - name: city
            mapping: City
          - name: region
            mapping: Region
          - name: postalCode
            mapping: PostalCode
          - name: country
            mapping: Country
      - name: Categories
        mapping: Categories
        properties:
          - name: id
            mapping: CategoryID
          - name: name
            mapping: CategoryName
          - name: description
            mapping: Description
      - name: Customers
        extends: Address
        mapping: Customers
        properties:
          - name: id
            mapping: CustomerID
          - name: name
            mapping: CompanyName
          - name: contact
            mapping: ContactName
          - name: phone
            mapping: ContactTitle
      - name: Employees
        extends: Address
        mapping: Employees
        properties:
          - name: id
            mapping: EmployeeID
          - name: lastName
            mapping: LastName
          - name: firstName
            mapping: FirstName
          - name: title
            mapping: Title
          - name: titleOfCourtesy
            mapping: TitleOfCourtesy
          - name: birthDate
            mapping: BirthDate
          - name: hireDate
            mapping: HireDate
          - name: phone
            mapping: HomePhone
          - name: reportsToId
            mapping: ReportsTo
      - name: Shippers
        mapping: Shippers
        properties:
          - name: id
            mapping: ShipperID
          - name: name
            mapping: CompanyName
          - name: phone
            mapping: Phone
      - name: Suppliers
        extends: Address
        mapping: Suppliers
        properties:
          - name: id
            mapping: SupplierID
          - name: name
            mapping: CompanyName
          - name: contact
            mapping: ContactName
          - name: phone
            mapping: Phone
          - name: homepage
            mapping: HomePage
      - name: Products
        mapping: Products
        properties:
          - name: id
            mapping: ProductID
          - name: name
            mapping: ProductName
          - name: supplierId
            mapping: SupplierID
          - name: categoryId
            mapping: CategoryID
          - name: quantity
            mapping: QuantityPerUnit
          - name: price
            mapping: UnitPrice
          - name: inStock
            mapping: UnitsInStock
          - name: onOrder
            mapping: UnitsOnOrder
          - name: reorderLevel
            mapping: ReorderLevel
          - name: discontinued
            mapping: Discontinued
      - name: Orders
        mapping: Orders
        properties:
          - name: id
            mapping: OrderID
          - name: customerId
            mapping: CustomerID
          - name: employeeId
            mapping: EmployeeID
          - name: orderDate
            mapping: OrderDate
          - name: requiredDate
            mapping: RequiredDate
          - name: shippedDate
            mapping: ShippedDate
          - name: shipViaId
            mapping: ShipVia
          - name: freight
            mapping: Freight
          - name: name
            mapping: ShipName
          - name: address
            mapping: ShipAddress
          - name: city
            mapping: ShipCity
          - name: region
            mapping: ShipRegion
          - name: postalCode
            mapping: ShipPostalCode
          - name: country
            mapping: ShipCountry
      - name: Orders.details
        mapping: Order Details
        properties:
          - name: orderId
            mapping: OrderID
          - name: productId
            mapping: ProductID
          - name: unitPrice
            mapping: UnitPrice
          - name: quantity
            mapping: Quantity
          - name: discount
            mapping: Discount
  - name: Oracle
    extends: default
    entities:
      - name: Address
      - name: Categories
        sequence: SQ_CATEGORIES
      - name: Customers
      - name: Employees
        sequence: SQ_EMPLOYEES
      - name: Shippers
        sequence: SQ_SHIPPERS
      - name: Suppliers
        sequence: SQ_SUPPLIERS
      - name: Products
        sequence: SQ_PRODUCTS
      - name: Orders
        sequence: SQ_ORDERS
      - name: Orders.details
        # sequence: SQ_ORDER_DETAILS
  - name: MongoDB
    extends: default
    entities:
      - name: Address
      - name: Categories
        sequence: SQ_CATEGORIES
        properties:
          - name: id
            mapping: _id
      - name: Customers
        properties:
          - name: id
            mapping: _id
      - name: Employees
        # extends: Address
        sequence: SQ_EMPLOYEES
        properties:
          - name: id
            mapping: _id
      - name: Shippers
        sequence: SQ_SHIPPERS
        properties:
          - name: id
            mapping: _id
      - name: Suppliers
        # extends: Address
        sequence: SQ_SUPPLIERS
        properties:
          - name: id
            mapping: _id
      - name: Products
        sequence: SQ_PRODUCTS
        properties:
          - name: id
            mapping: _id
      - name: Orders
        sequence: SQ_ORDERS
        properties:
          - name: id
            mapping: _id
sources:
  - name: Source
    mapping: default
    dialect: MySQL
    connection: ${ORM_CNN_SOURCE}
  - name: MySQL
    mapping: default
    dialect: MySQL
    connection: ${ORM_CNN_MYSQL}
  - name: MariaDB
    mapping: default
    dialect: MariaDB
    connection: ${ORM_CNN_MARIADB}
  - name: PostgreSQL
    mapping: default
    dialect: PostgreSQL
    connection: ${ORM_CNN_POSTGRES}
  - name: SqlServer
    mapping: default
    dialect: SqlServer
    connection: ${ORM_CNN_MSSQL}
  - name: Oracle
    mapping: Oracle
    dialect: Oracle
    connection: ${ORM_CNN_ORACLE}
  - name: MongoDB
    mapping: MongoDB
    dialect: MongoDB
    connection: ${ORM_CNN_MONGODB}
stages:
  - name: Source
    sources:
      - name: Source
  - name: MySQL
    sources:
      - name: MySQL
  - name: MariaDB
    sources:
      - name: MariaDB
  - name: PostgreSQL
    sources:
      - name: PostgreSQL
  - name: SqlServer
    sources:
      - name: SqlServer
  - name: Oracle
    sources:
      - name: Oracle
  - name: MongoDB
    sources:
      - name: MongoDB
