entities:
  - name: Devices
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        length: 32
        nullable: false
      - name: name
        nullable: false
      - name: type
        length: 32
        nullable: false
      - name: brand
        length: 32
        nullable: false
      - name: model
        length: 32
        nullable: false
      - name: so
        nullable: false
      - name: imei
        length: 16
      - name: imei2
        length: 16
      - name: mac
        length: 24
      - name: macBluetooth
        length: 24
      - name: ip
        length: 24
    relations:
      - name: components
        type: manyToOne
        from: id
        entity: Components
        to: deviceId
        composite: true
      - name: journeys
        type: manyToOne
        from: id
        entity: Journeys
        to: deviceId
      - name: files
        type: manyToOne
        from: id
        entity: Files
        to: deviceId
  #  son los componentes que componen un dispositivo, ejemplo: camara 1 , camara 2, microfono,gps , etc.
  - name: Components
    primaryKey: ["id"]
    properties:
      # el ID del componente debe ser establecido por el  dispositivo, ejemplo  deviceID + name , ejempo 233943849384483-cam01
      - name: id
        length: 64
        nullable: false
      - name: name
        length: 32
        nullable: false
      - name: type
        length: 32
        nullable: false
      - name: brand
        length: 32
        nullable: false
      - name: model
        length: 32
        nullable: false
      - name: deviceId
        length: 32
        nullable: false
    relations:
      - name: device
        from: deviceId
        entity: Devices
        to: id
      - name: files
        type: manyToOne
        from: id
        entity: Files
        to: componentId
  - name: DeviceStatuses
    primaryKey: ["id"]
    indexes:
      - name: time
        fields: ["time"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: deviceId
        length: 32
        nullable: false
      - name: journeyId
        type: integer
      - name: time
        type: datetime
        nullable: false
      - name: latitude
        type: decimal
      - name: longitude
        type: decimal
      - name: altitude
        type: decimal
      - name: cpu
        type: decimal
      - name: cpuTemperature
        type: decimal
      - name: batery
        type: decimal
      - name: wifiSignal
        type: decimal
    relations:
      - name: device
        from: deviceId
        entity: Devices
        to: id
      - name: journey
        from: journeyId
        entity: Journeys
        to: id
  # representa un trayecto, ejemplo de casa al colegio
  - name: Journeys
    primaryKey: ["id"]
    indexes:
      - name: deviceId
        fields: ["deviceId"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: deviceId
        length: 32
        nullable: false
      - name: startId
        type: integer
      - name: endId
        type: integer
    relations:
      - name: device
        from: deviceId
        entity: Devices
        to: id
      - name: start
        from: startId
        entity: DeviceStatuses
        to: id
      - name: end
        from: endId
        entity: DeviceStatuses
        to: id
      - name: statuses
        type: manyToOne
        composite: true
        from: id
        entity: DeviceStatuses
        to: journeyId
  - name: Files
    #  use MinIO for save files, field file is path
    primaryKey: ["id"]
    properties:
      #  el id es el fullpath del file, ejemplo: /deviceId/componentId/202202100922.mp3
      - name: id
        length: 255
        nullable: false
      # el tipo de file, ejemplo: audio|video
      - name: type
        length: 16
        nullable: false
      - name: deviceId
        length: 32
        nullable: false
      - name: componentId
        nullable: false
        length: 32
      - name: start
        type: datetime
      - name: endId
        type: datetime
    relations:
      - name: device
        from: deviceId
        entity: Devices
        to: id
      - name: component
        from: componentId
        entity: Components
        to: id
  - name: Groups
    primaryKey: ["id"]
    uniqueKey: ["name"]
    properties:
      - name: id
        length: 32
        default: lower(substring(replace(name," ","-"),0,32))
        nullable: false
      - name: name
        length: 32
        nullable: false
    relations:
      - name: members
        type: manyToOne
        from: id
        entity: GroupDevices
        to: deviceId
        composite: true
  - name: GroupDevices
    primaryKey: ["id"]
    uniqueKey: ["groupId", "deviceId"]
    properties:
      - name: id
        type: integer
        nullable: false
        autoincrement: true
      - name: deviceId
        length: 32
        nullable: false
      - name: groupId
        length: 32
        nullable: false
    relations:
      - name: group
        from: groupId
        entity: Groups
        to: id
      - name: device
        from: deviceId
        entity: Devices
        to: id

mappings:
  - name: default
dataSources:
  - name: postgres
    mapping: default
    dialect: postgres
    connection: $CNN_POSTGRES
stages:
  - name: default
    dataSources:
      - name: postgres
