CREATE ROLE
    "LOCATIONS" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD 'LOCATIONS';

CREATE ROLE
    "PARTIES" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD 'PARTIES';

CREATE ROLE
    "PARTY_ROLES" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD 'PARTY_ROLES';

CREATE ROLE
    "LEDGER_ACCOUNTS" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD 'LEDGER_ACCOUNTS';

CREATE ROLE
    "DEBTORS" SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN PASSWORD 'DEBTORS';